'name': 'build'

'env':
  'GO_VERSION': '1.24.4'

'on':
  'push':
    'branches':
    - '*'
    'tags':
    - 'v*'
  'pull_request':

'jobs':
  'test':
    'runs-on': '${{ matrix.os }}'
    'env':
      'GO111MODULE': 'on'
    'strategy':
      'fail-fast': false
      'matrix':
        'os':
        - 'ubuntu-latest'
        - 'macOS-latest'
        - 'windows-latest'
    'steps':
    - 'name': 'Checkout'
      'uses': 'actions/checkout@v2'
      'with':
        'fetch-depth': 0
    - 'name': 'Set up Go'
      'uses': 'actions/setup-go@v3'
      'with':
        'go-version': '${{ env.GO_VERSION }}'
    - 'name': 'Set up Go modules cache'
      'uses': 'actions/cache@v4'
      'with':
        'path': '~/go/pkg/mod'
        'key': "${{ runner.os }}-go-${{ hashFiles('go.sum') }}"
        'restore-keys': '${{ runner.os }}-go-'
    - 'name': 'Run tests'
      'shell': 'bash'
      'run': 'make VERBOSE=1 go-deps go-test'

  'build-release':
    'runs-on': 'ubuntu-latest'
    'needs': 'test'
    'steps':
    - 'name': 'Checkout'
      'uses': 'actions/checkout@v2'
      'with':
        'fetch-depth': 0
    - 'name': 'Set up Go'
      'uses': 'actions/setup-go@v3'
      'with':
        'go-version': '${{ env.GO_VERSION }}'
    - 'name': 'Set up Go modules cache'
      'uses': 'actions/cache@v4'
      'with':
        'path': '~/go/pkg/mod'
        'key': "${{ runner.os }}-go-${{ hashFiles('go.sum') }}"
        'restore-keys': '${{ runner.os }}-go-'
    - 'name': 'Run snapshot build'
      # Set a custom version string, since the checkout@v2 action does not seem
      # to know about the master branch, while the version script uses it to
      # count the number of commits within the branch.
      'run': 'make MSI=0 SIGN=0 VERBOSE=1 VERSION="v0.0.0-github" build-release'

  'notify':
    'needs':
    - 'build-release'
    # Secrets are not passed to workflows that are triggered by a pull request
    # from a fork.
    #
    # Use always() to signal to the runner that this job must run even if the
    # previous ones failed.
    'if':
      ${{
        always() &&
        github.repository_owner == 'AdguardTeam' &&
        (
          github.event_name == 'push' ||
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    'runs-on': 'ubuntu-latest'
    'steps':
    - 'name': 'Conclusion'
      'uses': 'technote-space/workflow-conclusion-action@v1'
    - 'name': 'Send Slack notif'
      'uses': '8398a7/action-slack@v3'
      'with':
        'status': '${{ env.WORKFLOW_CONCLUSION }}'
        'fields': 'repo, message, commit, author, workflow'
      'env':
        'GITHUB_TOKEN': '${{ secrets.GITHUB_TOKEN }}'
        'SLACK_WEBHOOK_URL': '${{ secrets.SLACK_WEBHOOK_URL }}'
